#!/bin/bash

# reset everything
#SBATCH --export=NONE

# number of nodes
#SBATCH --nodes=1# 

# number of tasks per node
#SBATCH --ntasks=4

# time you think your job will take (process will end after this time!)
#SBATCH --time=24:00:00

# number of gpus you want to run your job on
#SBATCH --gres=gpu:4

# memory needed
#SBATCH --mem=240G 

# which partition you want to send the job to (view partitions with 'sinfo')
#SBATCH --partition=gpu-medium

# email adress to contact with notifications
#SBATCH --mail-user=h.p.de.vos@fgga.leidenuniv.nl

# when to send notifications <BEGIN|END|FAIL|REQUEUE|ALL>
#SBATCH --mail-type="ALL"

# Load modules

#Pytorch

#Python 3.7+

echo "============LOAD TensorFlow============"
#module load Miniconda3/4.7.10
module load TensorFlow/2.1.0-fosscuda-2019b-Python-3.7.4
echo "============LOAD PyTorch============"
module load PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4

# cd to wd
cd /data/voshpde/pipeLine

# Install
pip install pyannote.core --user
pip install pyannote.audio==1.1.1 --user
pip install pydub
pip install librosa --user
pip install transformers --user


# run
python ASRpipeline.py /data/voshpde/wav_files/zipfiles/2014090301.wav  &
python ASRpipeline.py /data/voshpde/wav_files/zipfiles/2015041402.wav  &
python ASRpipeline.py /data/voshpde/wav_files/zipfiles/2015120101.wav  &
python ASRpipeline.py /data/voshpde/wav_files/zipfiles/2016061501.wav  &
wait

# 2014090301.wav  2015041402.wav  2015120101.wav  2016061501.wav  2017012401.wav